repo_location: "data/repositories"
repo_index_location: "data/repositoryIndexes"

llm_chat_completion_api_url: "https://api.groq.com/openai/v1/chat/completions"
llm_chat_completion_api_key: ""
llm_model: "llama-3.1-8b-instant"